### ISSUE TITLE
Taskbar infinite clicks

### ISSUE THREAD

**Issue by itsnottakenme** [Itsskiip/SClicker#1]
Thanks again for creating this! I notice a bug in the taskbar. When I let SClicker click TaskView or the down arrow for hidden tray icons SClicker clicks indefinitely.

Also changes the dwelling delay from 0.1s to 0.5s would make clicking more manageable although I think I can change this myself.

**Comment by Itsskiip** [comment]
Sorry for the wait! Did not expect you to get a response in so quickly.

I've fixed this in v0.2.0, and made it easier to modify the dwell time too. Let me know if you have any more requests!

**Comment by itsnottakenme** [comment]
Thanks it works really well now! The only improvement I can think of is to
have the tray icon change color depending on whether autoclick is enabled
or not (eg. Green for on, red for off, for example)

**Comment by Itsskiip** [comment]
I've added that now, enjoy :)

**Comment by itsnottakenme** [comment]
Thanks a lot for adding the on/off status toggle. I've been using SClicker
and it works great
